<a href="https://colab.research.google.com/github/alimunoz/sic_ai_2025_jun/blob/main/Slicing_Equipo2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 📌 1. **Slicing en arrays 1D**

```python
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60])
```

| Código    | Resultado             | Descripción                       |
| --------- | --------------------- | --------------------------------- |
| `a[1:4]`  | `[20 30 40]`          | Desde índice 1 hasta el 3         |
| `a[:3]`   | `[10 20 30]`          | Desde el inicio hasta el índice 2 |
| `a[3:]`   | `[40 50 60]`          | Desde índice 3 hasta el final     |
| `a[::2]`  | `[10 30 50]`          | Cada 2 elementos (paso 2)         |
| `a[::-1]` | `[60 50 40 30 20 10]` | Array invertido                   |

---

## 📌 2. **Slicing en arrays 2D (matrices)**

```python
b = np.array([[ 1,  2,  3],
              [ 4,  5,  6],
              [ 7,  8,  9]])
```

| Código          | Resultado                     | Descripción                        |
| --------------- | ----------------------------- | ---------------------------------- |
| `b[0:2, 1:3]`   | `[[2 3], [5 6]]`              | Filas 0–1, columnas 1–2            |
| `b[:, 1]`       | `[2 5 8]`                     | Toda la **columna 1**              |
| `b[1]`          | `[4 5 6]`                     | Toda la **fila 1**                 |
| `b[:2, :]`      | `[[1 2 3], [4 5 6]]`          | Filas 0 y 1, todas las columnas    |
| `b[::-1, ::-1]` | `[[9 8 7], [6 5 4], [3 2 1]]` | Matriz **invertida completamente** |

---

## 📌 3. **Slicing en arrays 3D**

```python
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
```

Visualización:

* Capa 0: `[[1, 2], [3, 4]]`
* Capa 1: `[[5, 6], [7, 8]]`

| Código       | Resultado        | Descripción                     |
| ------------ | ---------------- | ------------------------------- |
| `c[0, :, :]` | `[[1 2], [3 4]]` | Toda la **capa 0** completa     |
| `c[:, 1, :]` | `[[3 4], [7 8]]` | Segunda **fila** de cada capa   |
| `c[:, :, 0]` | `[[1 3], [5 7]]` | Primeros elementos de cada fila |

---

## 🎯 ¿Para qué sirve slicing?

* Extraer secciones de arrays sin copiar todo
* Cortar filas, columnas o bloques
* Aplicar operaciones por partes
* Indexar eficientemente sin bucles

---

In [ ]:
import numpy as np

# -------- ARRAY 1D --------
a = np.array([10, 20, 30, 40, 50, 60])
print("1D Array:", a)

print("a[1:4]       ->", a[1:4])      # [20 30 40]
print("a[:3]        ->", a[:3])       # [10 20 30]
print("a[3:]        ->", a[3:])       # [40 50 60]
print("a[::2]       ->", a[::2])      # [10 30 50]
print("a[::-1]      ->", a[::-1])     # [60 50 40 30 20 10]

# -------- ARRAY 2D --------
b = np.array([[ 1,  2,  3],
              [ 4,  5,  6],
              [ 7,  8,  9]])
print("\n2D Array:\n", b)

print("b[0:2, 1:3]  ->\n", b[0:2, 1:3])  # filas 0-1, columnas 1-2
print("b[:, 1]     ->", b[:, 1])        # toda la columna 1
print("b[1]        ->", b[1])           # toda la fila 1
print("b[:2, :]    ->\n", b[:2, :])     # filas 0-1, todas las columnas
print("b[::-1, ::-1]->\n", b[::-1, ::-1])# matriz invertida

# -------- ARRAY 3D --------
c = np.array([
    [[ 1,  2], [ 3,  4]],
    [[ 5,  6], [ 7,  8]]
])
print("\n3D Array:\n", c)

print("c[0, :, :]  ->\n", c[0, :, :])   # primera capa completa
print("c[:, 1, :]  ->\n", c[:, 1, :])   # segunda fila de cada capa
print("c[:, :, 0]  ->\n", c[:, :, 0])   # primer elemento de cada fila de cada capa


1D Array: [10 20 30 40 50 60]
a[1:4]       -> [20 30 40]
a[:3]        -> [10 20 30]
a[3:]        -> [40 50 60]
a[::2]       -> [10 30 50]
a[::-1]      -> [60 50 40 30 20 10]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b[0:2, 1:3]  ->
 [[2 3]
 [5 6]]
b[:, 1]     -> [2 5 8]
b[1]        -> [4 5 6]
b[:2, :]    ->
 [[1 2 3]
 [4 5 6]]
b[::-1, ::-1]->
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
c[0, :, :]  ->
 [[1 2]
 [3 4]]
c[:, 1, :]  ->
 [[3 4]
 [7 8]]
c[:, :, 0]  ->
 [[1 3]
 [5 7]]


In [ ]:
import numpy as np

# Crear array 3D de forma (2 bloques, 3 filas, 4 columnas)
arr3d = np.arange(2 * 3 * 4).reshape(2, 3, 4)
print("Array 3D:\n", arr3d)

# 1. Primera capa (bloque completo)
print("\n1. arr3d[0] ->\n", arr3d[0])

# 2. Todas las capas, fila 1, todas las columnas
print("\n2. arr3d[:, 1, :] ->\n", arr3d[:, 1, :])

# 3. Todas las capas, todas las filas, columna 2
print("\n3. arr3d[:, :, 2] ->\n", arr3d[:, :, 2])

# 4. Segunda capa (bloque 1), últimas dos filas
print("\n4. arr3d[1, 1:, :] ->\n", arr3d[1, 1:, :])

# 5. Última fila de cada capa
print("\n5. arr3d[:, -1, :] ->\n", arr3d[:, -1, :])

# 6. Primera columna de todas las filas de cada capa
print("\n6. arr3d[:, :, 0] ->\n", arr3d[:, :, 0])

# 7. Invertir el orden de las capas
print("\n7. arr3d[::-1] ->\n", arr3d[::-1])

# 8. Slicing + condición: todos los elementos > 15 en capa 1
print("\n8. arr3d[1][arr3d[1] > 15] ->\n", arr3d[1][arr3d[1] > 15])


Array 3D:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

1. arr3d[0] ->
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

2. arr3d[:, 1, :] ->
 [[ 4  5  6  7]
 [16 17 18 19]]

3. arr3d[:, :, 2] ->
 [[ 2  6 10]
 [14 18 22]]

4. arr3d[1, 1:, :] ->
 [[16 17 18 19]
 [20 21 22 23]]

5. arr3d[:, -1, :] ->
 [[ 8  9 10 11]
 [20 21 22 23]]

6. arr3d[:, :, 0] ->
 [[ 0  4  8]
 [12 16 20]]

7. arr3d[::-1] ->
 [[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]

8. arr3d[1][arr3d[1] > 15] ->
 [16 17 18 19 20 21 22 23]
