<a href="https://colab.research.google.com/github/davidlealo/sic_ai_2025_jun/blob/main/05deeplearning/clase_36.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Guía detallada de uso de tensores en TensorFlow

> **Requisitos previos:** Python 3.x, `tensorflow>=2.0`, `numpy`  
> **Nota:** En TensorFlow 2.x la ejecución es *eager* por defecto, lo que significa que las operaciones se evalúan inmediatamente.

---

## 1) De listas / NumPy a `tf.Tensor`

```python
import numpy as np
import tensorflow as tf

# a) Desde un arreglo de NumPy (especificando dtype)
a = np.array([1, 2, 3], dtype=np.int32)

# b) Desde una lista de Python
b = [4, 5, 6]

# Convertimos a tensores
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)  # Inferirá dtype=int32

print(t_a)
print(t_b)
```

**Explicación**  
- `tf.convert_to_tensor` convierte listas, arrays de NumPy u otros tensores a un `tf.Tensor`.
- El parámetro `dtype` controla el tipo de dato, por ejemplo `tf.float32`, `tf.int32`, etc.

```python
# Verificar si un objeto es un tensor
print(tf.is_tensor(a), tf.is_tensor(t_a))  # -> (False, True)
```

---

## 2) Tensores pre-llenados y constantes

```python
# Tensor de unos con forma (2, 3)
t_ones = tf.ones((2, 3))
print(t_ones.shape)   # TensorShape([2, 3])
print(t_ones.numpy()) # Convierte a ndarray
```

```python
# Constante con dtype explícito
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
print(const_tensor)
```

**Notas**
- `tensor.numpy()` devuelve un `np.ndarray`, útil para inspeccionar resultados.
- Si no se especifica `dtype`, TensorFlow lo infiere automáticamente.

---

## 3) `tf.fill` vs `tf.ones`

```python
t_fill = tf.fill((2, 3), 1)
print(t_fill)
```

**Diferencia clave**  
- `tf.ones`: para inicializar tensores con unos.  
- `tf.fill`: para inicializar con cualquier valor escalar.

---

## 4) Codificación one-hot

```python
oh = tf.one_hot([0, 1, 2], depth=4)
print(oh)
```

**Uso común**: Representar categorías como vectores binarios.

---

## 5) Cambiar tipo y forma del tensor

```python
# a) Cambiar tipo
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new.dtype)

# b) Transponer
t = tf.random.uniform(shape=(3, 5))
t_tr = tf.transpose(t)
print(t.shape, '-->', t_tr.shape)

# c) Reshape
t = tf.zeros((30,))
t_reshape = tf.reshape(t, shape=(5, 6))
print(t_reshape.shape)

# d) Squeeze
t = tf.zeros((1, 2, 1, 4, 1))
t_sqz = tf.squeeze(t, axis=(2, 4))
print(t.shape, '-->', t_sqz.shape)
```

---

## 6) Tensores aleatorios

```python
tf.random.set_seed(1)

t1 = tf.random.uniform(shape=(5, 2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5, 2), mean=0.0, stddev=1.0)
```

---

## 7) Operaciones básicas

```python
# Multiplicación elemento a elemento
t3 = tf.multiply(t1, t2)
print(t3.numpy())

# Media por columnas
t4 = tf.math.reduce_mean(t1, axis=0)
print(t4)
```

---

## 8) Producto matricial

```python
# (5x2) @ (5x2)^T
t5 = tf.linalg.matmul(t1, t2, transpose_b=True)
print(t5.numpy())

# (5x2)^T @ (5x2)
t6 = tf.linalg.matmul(t1, t2, transpose_a=True)
print(t6.numpy())
```

---

## 9) Norma L2

```python
norm_t1 = tf.norm(t1, ord=2, axis=1)
print(norm_t1.numpy())

# Verificación con NumPy
check = np.sqrt(np.sum(np.square(t1.numpy()), axis=1))
print(check)
```

---

## 10) Resumen de funciones útiles

- `t.shape` → forma del tensor.  
- `t.dtype` → tipo de dato.  
- `t.numpy()` → convierte a `np.ndarray`.  
- Crear: `tf.constant`, `tf.ones`, `tf.zeros`, `tf.fill`, `tf.random.uniform`, `tf.random.normal`, `tf.one_hot`.  
- Transformar: `tf.cast`, `tf.reshape`, `tf.transpose`, `tf.squeeze`.  
- Operar: `tf.add`, `tf.subtract`, `tf.multiply`, `tf.divide`, `tf.reduce_sum`, `tf.reduce_mean`, `tf.linalg.matmul`, `tf.norm`.

---

## Errores comunes

- **Formas incompatibles** en `matmul`.  
- **Dtypes diferentes** (usar `tf.cast` para igualarlos).  
- **Resultados no reproducibles** (usar `tf.random.set_seed`).  
- **Confusión con `axis`**: `axis=0` → a lo largo de filas, `axis=1` → a lo largo de columnas.


In [1]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [2]:
import tensorflow as tf
import numpy as np

In [3]:
np.set_printoptions(precision=3)

In [ ]:
# Instalación (si hace falta en Colab)
# !pip install -q tensorflow numpy

import numpy as np
import tensorflow as tf

print(tf.__version__)


In [4]:
# a) Desde un arreglo de NumPy (especificando dtype)
a = np.array([1, 2, 3], dtype=np.int32)

# b) Desde una lista de Python
b = [4, 5, 6]

# Convertimos a tensores
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)  # inferirá dtype=int32

print(t_a)
print(t_b)


tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [5]:
# Verificar si un objeto es un tensor
print(tf.is_tensor(a), tf.is_tensor(t_a))  # -> (False, True)


False True


In [6]:
# Tensor de unos con forma (2, 3)
t_ones = tf.ones((2, 3))
print(t_ones.shape)   # TensorShape([2, 3])
t_ones.numpy()        # Convertir a ndarray para "ver" los valores


(2, 3)


array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [7]:
# Constante con dtype explícito
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
print(const_tensor)   # tf.Tensor([1.2 5. 3.142...], shape=(3,), dtype=float32)


tf.Tensor([1.2   5.    3.142], shape=(3,), dtype=float32)


In [8]:
# Rellena con un escalar dado
t_fill = tf.fill((2, 3), 1)  # igual forma que (2, 3) de ones
print(t_fill)                # dtype=int32 por defecto en este ejemplo


tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [9]:
t_ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
t_zeros = tf.zeros((2, 3))
t_zeros

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [11]:
# tf.one_hot(indices, depth) -> matriz (len(indices) x depth)
oh = tf.one_hot([0, 1, 2], depth=4)
print(oh)  # shape=(3, 4), dtype=float32 por defecto


tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]], shape=(3, 4), dtype=float32)


In [12]:
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new.dtype)  # int64


<dtype: 'int64'>


In [13]:
t = tf.random.uniform(shape=(3, 5))  # 3 filas, 5 columnas
t_tr = tf.transpose(t)
print(t.shape, '-->', t_tr.shape)    # (3, 5) --> (5, 3)


(3, 5) --> (5, 3)


In [14]:
t = tf.zeros((30,))
t_reshape = tf.reshape(t, shape=(5, 6))
print(t_reshape.shape)  # (5, 6)


(5, 6)


In [15]:
t = tf.zeros((1, 2, 1, 4, 1))
t_sqz = tf.squeeze(t, axis=(2, 4))   # quita ejes 2 y 4 (ambos de tamaño 1)
print(t.shape, '-->', t_sqz.shape)   # (1, 2, 1, 4, 1) --> (1, 2, 4)


(1, 2, 1, 4, 1) --> (1, 2, 4)


In [16]:
tf.random.set_seed(1)  # misma salida cada vez que corras esta celda

t1 = tf.random.uniform(shape=(5, 2), minval=-1.0, maxval=1.0)  # U(-1, 1)
t2 = tf.random.normal(shape=(5, 2), mean=0.0, stddev=1.0)      # N(0, 1)

t1, t2  # obs: los valores exactos pueden variar si cambias la seed


(<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.67 ,  0.803],
        [ 0.262, -0.131],
        [-0.416,  0.285],
        [ 0.952, -0.13 ],
        [ 0.32 ,  0.21 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[ 0.403, -1.088],
        [-0.063,  1.337],
        [ 0.712, -0.489],
        [-0.764, -1.037],
        [-1.252,  0.021]], dtype=float32)>)

In [17]:
# Multiplicación elemento a elemento (Hadamard)
t3 = tf.multiply(t1, t2)
print(t3.numpy())  # ver como ndarray


[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


In [18]:
# Media por columnas (axis=0)
t4 = tf.math.reduce_mean(t1, axis=0)
print(t4)          # shape=(2,)


tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)


## Puedes revisar los datsets de tf en:


https://www.tensorflow.org/datasets/catalog/overview

## Revisar material año 2024

https://github.com/davidlealo/sic_ai_2024/blob/main/006_deep_learning/%5Bsabado-14-septiembre%5DClase27_SIC_AI_2024.ipynb


# Llegamos hasta la página 128